### ISSUE TITLE
Error in stringr::str_match

### ISSUE THREAD

**Issue by Lakens** [rubenarslan/codebook#16]
Love this idea - sorely needed to have good meta-data, and will play with this and try it out. I tried to create a codebook for a large rather messy data I have, namely the GSS data (I checked with Release 2 and 3), which can be downloaded here: [GSS_data](http://gss.norc.org/get-the-data/stata)
This is a rather large datafile. I ran the code below, and received an error (pasted below the code). I just wanted to let you know, but I don't find it unreasonable that codebook does not work on this datafile by default without changing anything. Nevertheless, I wanted to let you know in case the error is something worthwhile to fix. 

`library(haven)`
`library(codebook)`
`results = haven::read_dta("GSS7216_R2.DTA", encoding = "windows-1252")`
`codebook(results)`

**The error I get when generating a html markdown file is:** 

Quitting from lines 58-71 (codebook.Rmd) 

Error in stringr::str_match(names(stats::na.omit(choices)), "\\[?([0-9-]+)(\\]|:)")[,  : 
  subscript out of bounds
Calls: <Anonymous> ... withCallingHandlers -> withVisible -> eval -> eval -> plot_labelled

**Comment by rubenarslan** [comment]
Daniel @Lakens thanks for the bug report! If you re-install from Github using `devtools::install_github("rubenarslan/codebook")` you should be able to run `codebook` without problems. I've included the GSS in my tests. I only looked at the first 200 variables, but it seems to work quite well out-of-the-box, only some items have "undeclared missings".

**Comment by rubenarslan** [comment]
@Lakens I've now tested that I can generate a codebook for the entire GSS, which required one other bug fix. Seems to work now (it generates a 500MB HTML doc which I can't easily browse). I added code for parallelising the generation to speed it up. On a mac, just call

```r
knitr::opts_chunk$set(dev = "CairoPNG")
library(future)
plan(multicore(workers = 3))
```

before calling the `codebook` function.
