### ISSUE TITLE
`rownames` error in `codebook_missingness`

### ISSUE THREAD

**Issue by stefvanbuuren** [rubenarslan/codebook#20]
In `codebook 0.5.8` using the dev version of `mice` I get:

    library(codebook)
    data("bfi")
    codebook_missingness(bfi)
    Error in `rownames<-`(`*tmp*`, value = table(pat)) : 
      attempt to set 'rownames' on an object with no dimensions

Could you check?

**Comment by rubenarslan** [comment]
I get the same error with

```r
mice::md.pattern(mtcars)
```

So I think it's unrelated to my post-processing in `codebook_missingness`.

**Comment by stefvanbuuren** [comment]
In `mice 3.0.0` the statement `mice::md.pattern(mtcars)` works. However, `mice::md.pattern(bfi)` still fails. I found out that this is a different issue, apparently caused by one column that is entirely `NA` in the `bfi` data. We will repair this.

**Comment by stefvanbuuren** [comment]
Repaired in `mice 3.0.2`
