### ISSUE TITLE
DDI

### ISSUE THREAD

**Issue by DougManuel** [rubenarslan/codebook#27]
Is DDI on your radar? https://www.ddialliance.org

Over 10K databases on ICPSR alone.  https://www.icpsr.umich.edu/icpsrweb/

**Comment by rubenarslan** [comment]
Yes, I would look into it again when a new [DDIwR](https://github.com/dusadrian/DDIwR) version is released by @dusadrian. Problem now is that it's a very crufty standard and few open tools exist.

**Comment by dusadrian** [comment]
Version 0.3 of the package [DDIwR](https://github.com/dusadrian/DDIwR) has just been submitted to CRAN, hope it's useful.
