### ISSUE TITLE
codebook() function throws an error

### ISSUE THREAD

**Issue by jobreu** [rubenarslan/codebook#36]
When I knit a codebook with the codebook() function I get the following error message (shown in the HTML output):
## Error in env_bind(mask, ... = env_get(current_env(), "...")): could not find function "env_bind"
This seems to be an issue with the new version of rlang (I have 0.4.0 installed).

**Comment by kwiebels** [comment]
I get the same error. When I add `library(rlang)` in the first chunk it works. I also have rlang version 0.4.0 installed.

**Comment by rubenarslan** [comment]
Can you try `update.packages(ask = F, rebuild = T)`? I could reproduce the problem when I updated only rlang, but not when I updated all relevant packages.

**Comment by kwiebels** [comment]
Yup, that fixes it for me.

**Comment by rubenarslan** [comment]
Great. That also explains why I got no note from CRAN for this problem. Thanks for the reports!

**Comment by kwiebels** [comment]
Awesome, thanks for the quick reply!
