### ISSUE TITLE
Skimr v2 release soon

### ISSUE THREAD

**Issue by elinw** [rubenarslan/codebook#40]
Skimr v2 is going to be released very soon.  You use `skim_to_wide()` but actually with the new API  the object defaults to wide. However there are other changes that might break things for codebook.  Please take a look and let us know if there are problems you can't solve.

**Comment by rubenarslan** [comment]
hi @elinw, yeah these are breaking changes for me. you now prefix the columns by variable type, even when it's nominally the same column (e.g. numeric.mean and POSIXct.mean). If I want one table, like [here](https://rubenarslan.github.io/codebook_gallery/PTSD.html#codebook_table), not the display by type you favour for the console, how should I go about it in a forward-thinking manner?

**Comment by elinw** [comment]
What you would need to do is to change them to characters, then you can put them all into one column.  As numbers they can't be in the same column since the mean of a date and the mean of a numeric aren't compatible.

**Comment by rubenarslan** [comment]
Previously, this was how `skim_to_wide` worked already, wasn't it? 
Maybe drop the function entirely if the result changes so much? I don't think anyone who used `skim_to_wide` before can continue using the new function.

I think my use case might not be that uncommon (wanting to take the skimr summary table out of the console/HTML in a readable, non-super-wide spreadsheet). 
So, can I request a function to do this? Just casting to character isn't trivial (e.g. how many digits when casting numeric to character). Also, the variable names are inconsistent across types, even though they mean the same thing (p0 = min, p50 = median, p100 = max).

```r
iris$bla <- rep(c(T, F), length.out = nrow(iris))
iris$date <- rep(c(as.POSIXct(Sys.time()), as.POSIXct(Sys.Date())), length.out = nrow(iris))
x <- skim(iris)

to_wide <- function(x) {
  vars <- names(x)
  names(x) <- gsub(".*\\.","",vars)
  x <- sapply(x, FUN = as.character)

  xdf <- as.data.frame(x)
  xdf
}

to_wide(skim(iris))
```

**Comment by michaelquinn32** [comment]
Hi Ruben!

Sorry for the inconvenience.

We previously stored numeric and text rendered versions of all of the cells in the output table, which was not especially transparent to users, and created a host of different unicode conversion errors. The new version doesn't do this, but the cost, as you have noted, is that we cannot store columns of different data types together. In fact, this isn't something that you can really do at all in R.

For example, try combining a POSIXct and numeric value

```
Sys.time()
#> [1] "2019-11-13 18:15:15 EST"

c(1, Sys.time())
#> [1]          1 1573686904
```

We saw this first when processing a data frame that had two different date format columns; the "means" of each meant very different things.

You could convert every column to character of the partitioned result, and then combine the data frames. This would work in some instances, as long as you weren't too concerned about the possible unicode problems that converting would cause.

Here's a place to start:

     library(skimr)                                                              
     skimr::skim(iris) %>%                                                       
       skimr::partition() %>%                                                    
       lapply(dplyr::mutate_all, as.character) %>%                               
       dplyr::bind_rows() %>%                                                    
       as.data.frame()                                                           
     #>   skim_variable n_missing complete_rate ordered n_unique                 
     #> 1       Species         0             1   FALSE        3                 
     #> 2  Sepal.Length         0             1    <NA>     <NA>                 
     #> 3   Sepal.Width         0             1    <NA>     <NA>                 
     #> 4  Petal.Length         0             1    <NA>     <NA>                 
     #> 5   Petal.Width         0             1    <NA>     <NA>                 
     #>                  top_counts             mean                sd   p0  p25 
     #> 1 set: 50, ver: 50, vir: 50             <NA>              <NA> <NA> <NA> 
     #> 2                      <NA> 5.84333333333333 0.828066127977863  4.3  5.1 
     #> 3                      <NA> 3.05733333333333 0.435866284936698    2  2.8 
     #> 4                      <NA>            3.758  1.76529823325947    1  1.6 
     #> 5                      <NA> 1.19933333333333 0.762237668960346  0.1  0.3 
     #>    p50  p75 p100  hist                                                   
     #> 1 <NA> <NA> <NA>  <NA>                                                   
     #> 2  5.8  6.4  7.9 ▆▇▇▅▂                                                   
     #> 3    3  3.3  4.4 ▁▆▇▂▁                                                   
     #> 4 4.35  5.1  6.9 ▇▁▆▇▂                                                   
     #> 5  1.3  1.8  2.5 ▇▁▇▅▃                                                   
                                                                                 
<sup>Created on 2019-11-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by elinw** [comment]
The fact that there are or could be different names for the "same" calculations on different classes has always been true.  We've announced that this new version with major changes was coming in release notes for 1.0 updates for over a year.  (Since 12.1.2018)

To do Michael's on your augmented data.

```
library(skimr)                                                              
 skimr::skim(iris) %>%                                                       
   skimr::partition() %>%                                                    
   lapply(dplyr::mutate_all, as.character) %>%                               
   dplyr::bind_rows() %>%                                                    
   as.data.frame() 

  skim_variable n_missing complete_rate ordered n_unique                top_counts
1       Species         0             1   FALSE        3 set: 50, ver: 50, vir: 50
2           bla         0             1    <NA>     <NA>                      <NA>
3  Sepal.Length         0             1    <NA>     <NA>                      <NA>
4   Sepal.Width         0             1    <NA>     <NA>                      <NA>
5  Petal.Length         0             1    <NA>     <NA>                      <NA>
6   Petal.Width         0             1    <NA>     <NA>                      <NA>
7          date         0             1    <NA>        2                      <NA>
              mean            count                sd   p0  p25  p50  p75 p100  hist
1             <NA>             <NA>              <NA> <NA> <NA> <NA> <NA> <NA>  <NA>
2              0.5 FAL: 75, TRU: 75              <NA> <NA> <NA> <NA> <NA> <NA>  <NA>
3 5.84333333333333             <NA> 0.828066127977863  4.3  5.1  5.8  6.4  7.9 ▆▇▇▅▂
4 3.05733333333333             <NA> 0.435866284936698    2  2.8    3  3.3  4.4 ▁▆▇▂▁
5            3.758             <NA>  1.76529823325947    1  1.6 4.35  5.1  6.9 ▇▁▆▇▂
6 1.19933333333333             <NA> 0.762237668960346  0.1  0.3  1.3  1.8  2.5 ▇▁▇▅▃
7             <NA>             <NA>              <NA> <NA> <NA> <NA> <NA> <NA>  <NA>
                  min                 max              median
1                <NA>                <NA>                <NA>
2                <NA>                <NA>                <NA>
3                <NA>                <NA>                <NA>
4                <NA>                <NA>                <NA>
5                <NA>                <NA>                <NA>
6                <NA>                <NA>                <NA>
7 2019-11-13 19:00:00 2019-11-14 01:17:19 2019-11-13 22:08:39

```

I think that's reasonable as a `to_wide()` function. 

I think that there is no way to deal with the differing names outside of defining your own `sfl`s. 
https://github.com/rubenarslan/codebook/issues/40

**Comment by elinw** [comment]
So what makes sense to me is that you would incorporate this into your code.  Here is an example where you would deal with the different naming issue.

```
y <- iris
y$bla <- rep(c(T, F), length.out = nrow(y))
y$date <- rep(c(as.POSIXct(Sys.time()), as.POSIXct(Sys.Date())), 
              length.out = nrow(y))


skim_cb <- skim_with(
  POSIXct = sfl(
    p50 = ~median(., na.rm = TRUE),
    p0 = ~min(., na.rm = TRUE),
    p50 = ~max(., na.rm = TRUE),
    median = NULL,
    max = NULL,
    min = NULL
  )
)

skim_cb(y) %>%                                                       
  skimr::partition() %>%                                                    
  lapply(dplyr::mutate_all, as.character) %>%                               
  dplyr::bind_rows() %>%                                                    
  as.data.frame()  

  skim_variable n_missing complete_rate ordered n_unique                top_counts
1       Species         0             1   FALSE        3 set: 50, ver: 50, vir: 50
2           bla         0             1    <NA>     <NA>                      <NA>
3  Sepal.Length         0             1    <NA>     <NA>                      <NA>
4   Sepal.Width         0             1    <NA>     <NA>                      <NA>
5  Petal.Length         0             1    <NA>     <NA>                      <NA>
6   Petal.Width         0             1    <NA>     <NA>                      <NA>
7          date         0             1    <NA>        2                      <NA>
              mean            count                sd                  p0  p25
1             <NA>             <NA>              <NA>                <NA> <NA>
2              0.5 FAL: 75, TRU: 75              <NA>                <NA> <NA>
3 5.84333333333333             <NA> 0.828066127977863                 4.3  5.1
4 3.05733333333333             <NA> 0.435866284936698                   2  2.8
5            3.758             <NA>  1.76529823325947                   1  1.6
6 1.19933333333333             <NA> 0.762237668960346                 0.1  0.3
7             <NA>             <NA>              <NA> 2019-11-13 19:00:00 <NA>
                  p50  p75 p100  hist
1                <NA> <NA> <NA>  <NA>
2                <NA> <NA> <NA>  <NA>
3                 5.8  6.4  7.9 ▆▇▇▅▂
4                   3  3.3  4.4 ▁▆▇▂▁
5                4.35  5.1  6.9 ▇▁▆▇▂
6                 1.3  1.8  2.5 ▇▁▇▅▃
7 2019-11-14 20:21:49 <NA> <NA>  <NA>

```

What I think would be good is if you want to use the consistent naming that you add your own renamed skimmers for what you support so it is exactly the way you want it.  We explain how to do this in a package in this vignette.
https://docs.ropensci.org/skimr/articles/Supporting_additional_objects.html

Elin

**Comment by rubenarslan** [comment]
Hey @elinw and @michaelquinn32, thanks for engaging with my questions.

I am not complaining about not being given enough notice, sorry if it came across that way.

I realise that we cannot store disparate types in one column. Like I said, I think what I want to do is reasonable to do in some cases, although I see it's not your main focus. But as you can see from your output, coercion using `as.character` isn't very nice-looking (e.g. doesn't respect `digits`) and I think you did something else in v1. 

If it was trivial to do, I think everybody patching together their own function _may_ be desirable, so you do not over-extend yourselves (as this is not how you want skimr to be mainly used). 
But I think it's non-trivial, so it seems like this might lead to many half-assed not-quite-right solutions out there, so maybe you putting it in skimr would be a way to avoid that situation.

Regarding the inconsistent naming, I should have probably kept this out of this discussion, but since you're going to have a major API change anyway, I wanted to question the rationale behind keeping inconsistent names. I think it's confusing even for the main use case of skimr, not just when wanting to make a wide table.

Lastly, you did not react to this, but I feel quite strongly that you should simply drop `skim_to_wide` from v2 because it isn't just deprecated, it returns something very very different. I think the `.Deprecated` message suggests we can still expect the function to do what it used to (maybe I'm wrong to have this expectation).

**Comment by elinw** [comment]
Of course V1 was totally different because there was the long object with the "formatted" column that stored the formatted string. In your customization of the skimmers you could include the necessary code to round the results to a specific number of digits.  You could even write your own code to make that configurable if desired.

**Comment by elinw** [comment]
So this I think is what you probably would want to do in general, but obviously you will have specific opinions.  And you could make it as flexible as you want.

```
y <- iris
y$bla <- rep(c(T, F), length.out = nrow(y))
y$date <- rep(c(as.POSIXct(Sys.time()), as.POSIXct(Sys.Date())), 
              length.out = nrow(y))



skim_cb <- skim_with(
  POSIXct = sfl(
    p0 = ~as.character(min(., na.rm = TRUE)),
    p50 = ~as.character(median(., na.rm = TRUE)),
    p100 = ~as.character(max(., na.rm = TRUE)),
    median = NULL,
    max = NULL,
    min = NULL
  ),
  numeric = sfl(
    mean = ~ as.character(format(mean(., na.rm = TRUE), digits =2)),
    sd = ~ as.character(format(sd(., na.rm = TRUE), digits =2)),
    p0 = ~as.character(format(min(., na.rm = TRUE), digits = 2)),
    p25 = ~as.character(quantile(., probs = c(.25), na.rm = TRUE)),
    p50 = ~as.character(median(., na.rm = TRUE)),
    p75 = ~as.character(quantile(., probs = c(.75), na.rm = TRUE)),
    p100 = ~as.character(max(., na.rm = TRUE))
    
  ),
  logical = sfl(
    mean = ~ as.character(format(mean(., na.rm = TRUE), digits =2))
  )
)

skim_cb(y) %>%                                                       
  skimr::partition() %>%                                                    
  dplyr::bind_rows() %>%                                                    
  as.data.frame()  
```
```
  skim_variable n_missing complete_rate ordered n_unique                top_counts mean
1       Species         0             1   FALSE        3 set: 50, ver: 50, vir: 50 <NA>
2           bla         0             1      NA       NA                      <NA>  0.5
3  Sepal.Length         0             1      NA       NA                      <NA>  5.8
4   Sepal.Width         0             1      NA       NA                      <NA>  3.1
5  Petal.Length         0             1      NA       NA                      <NA>  3.8
6   Petal.Width         0             1      NA       NA                      <NA>  1.2
7          date         0             1      NA        2                      <NA> <NA>
             count   sd                  p0  p25                 p50  p75
1             <NA> <NA>                <NA> <NA>                <NA> <NA>
2 FAL: 75, TRU: 75 <NA>                <NA> <NA>                <NA> <NA>
3             <NA> 0.83                 4.3  5.1                 5.8  6.4
4             <NA> 0.44                   2  2.8                   3  3.3
5             <NA>  1.8                   1  1.6                4.35  5.1
6             <NA> 0.76                 0.1  0.3                 1.3  1.8
7             <NA> <NA> 2019-11-13 19:00:00 <NA> 2019-11-14 07:46:16 <NA>
                 p100  hist
1                <NA>  <NA>
2                <NA>  <NA>
3                 7.9 ▆▇▇▅▂
4                 4.4 ▁▆▇▂▁
5                 6.9 ▇▁▆▇▂
6                 2.5 ▇▁▇▅▃
7 2019-11-14 20:32:32  <NA>
```
I think there is a lot you could do to make it the way you want and being able to make parts of it configurable.

**Comment by elinw** [comment]
What is `skim_to_wide_labelled()`?
https://github.com/rubenarslan/codebook/blob/7cfb326cf85c3322e359fff47d69967b6cb037c7/R/codebook.R#L474

Also this
https://github.com/rubenarslan/codebook/blob/7cfb326cf85c3322e359fff47d69967b6cb037c7/R/codebook.R#L480

is a hard coded list and I think it is probably based on the assumption that you will never have certain kinds of variables (e.g. time series).  Probably specifically numeric, factor, logical, character ... any others? As shown above it is simple to deal with the different naming of min and max/p0 p100, but since you have hard coded there are you very committed to keeping things like n? We decided `n` was redundant since it is the same for every column in the data frame by definition and we added `complete_rate`  as  (n-missing)/n as more useful.   Do you want to switch to those or are you committed to the old ones?

**Comment by elinw** [comment]
I believe that you could add the following to your code and have minimal impact. I'm not totally sure on the sfl because I don't know about your metadata and what is being joined from there.  But it should work with minor modifications.  I have tried it on both `codebook_data` from your vignette and some of the sample data sets.

Somewhere also you are using `skim_with_defaults` and you should get rid of that since it's not  not necessary any more.  

I think you could also for example make the skimmers configurable by changing digits to a variable and then allowing it to be set.

https://gist.github.com/elinw/8d0a5c58bda19d9a7fddb6f1b4974ff9

**Comment by elinw** [comment]
@rubenarslan   Can you give some feedback on this? We are ready to  release V2  and this is the thing preventing it.  @michaelquinn32

**Comment by rubenarslan** [comment]
Hi @elinw thanks so much for your help and advice. I'm on parental leave right now and I'm trying to find time to update and test the codebook package (I would like to roll in some other changes I made), but please don't let that keep you.

**Comment by elinw** [comment]
Cool and congratulations! @michaelquinn32  can tell you that it's very hard to get anything done!

**Comment by rubenarslan** [comment]
finally got around to it. sorry for the delay and thanks for the help.
