### ISSUE TITLE
'skim_with_defaults' is not an exported object from 'namespace:skimr' '

### ISSUE THREAD

**Issue by cloversleaves** [rubenarslan/codebook#43]
Thank you for the package. I usually use codebook_table(), this error was generated using codebook_browser(), but am receiving the above skimr error either way. Scrolling through issues there was mention of this, but I wasn't certain of the conclusion -- if any. Thank you, again; helpful package.

**Comment by rubenarslan** [comment]
it's an error I still need to fix but haven't because I'm on parental leave and haven't found the time. watch this space for an update. you can downgrade skimr to below 2.0.0 to make it work using `devtools::install_version`

**Comment by cloversleaves** [comment]
Thank you for the tips-- I understand. Glad to hear you are busy being a new parent.

**Comment by cloversleaves** [comment]
(fyi, using codebook 0.8.1 didn't work with skimr 2.0.0 for me but seems like it works ok with skimr 1.0.7)

**Comment by rubenarslan** [comment]
should now be fixed, 0.8.2 is on CRAN (binaries are still being built). thanks for your patience.

**Comment by cloversleaves** [comment]
Thank you!
