### ISSUE TITLE
Specifying a number of digits for mean and SD in the codebook table

### ISSUE THREAD

**Issue by JanaJarecki** [rubenarslan/codebook#54]
I tried setting `options(digits = 2)` in knitr, but this failed to affect the digits of the mean and sd column in the codebook table. Is there a different option to specify digits?

![image](https://user-images.githubusercontent.com/9809311/90974419-558ed580-e52b-11ea-87b7-3e7195d591d7.png)

**Comment by rubenarslan** [comment]
DT doesn't respect options(digits) but now defaults to two significant digits
