### ISSUE TITLE
Typo in `inst/_codebook.Rmd`, "#Variables" output as text rather than header

### ISSUE THREAD

**Issue by ntrlshrp** [rubenarslan/codebook#56]
**Behavior**
As you can see in your [Tutorial](https://rubenarslan.github.io/codebook/articles/codebook_tutorial.html), the Codebook output at the bottom includes `##Variables` as text just below the Metadata section (while my homemade Codebooks include `#Variables` as text). 

**Expected Behavior**
The floating table of contents and the (R)markdown both capture a Variables section with a `Variables` header in the Codebook.

**Fix**
If I adjust line 29 of the `inst/_codebook.Rmd` in my cloned local `codebook` repository from

```
`r ifelse(detailed_variables || detailed_scales, paste0(indent, "Variables"),"")
```

 to

```
`r ifelse(detailed_variables || detailed_scales, paste0(indent, "# Variables"),"")
```
 ,

I'm able to print out working Codebooks at home where the floating table of contents and the markdown both capture a Variables section with a `Variables` header.

**Comment by rubenarslan** [comment]
Thanks, I know about this problem, but always forget to fix it. You can install from Github to get the fix.
