### ISSUE TITLE
codebook() knits a seemingly blank .html file

### ISSUE THREAD

**Issue by nsunami** [rubenarslan/codebook#61]
I was trying to knit [this .rmd file](https://github.com/nsunami/dissertation/blob/master/codebooks/Study1a.Rmd) into a .html, but it produces a [seemingly blank .html file](https://github.com/nsunami/dissertation/blob/master/codebooks/Study1a.html). 
I do not see any errors on my console or RMarkdown. Does anyone have any idea what would be causing this?
(I really want to use this wonderful package in my project!)

**Comment by rubenarslan** [comment]
Hi @nsunami 
That is odd. Can you try removing `, include=FALSE`?

**Comment by nsunami** [comment]
Thanks for the reply @rubenarslan! 
I removed the `include=FALSE` in  the `knitr::opts_chunk$set()` and the resulting .html includes the codebook.
Thank you so much!
