### ISSUE TITLE
Problems with Codebook generator app

### ISSUE THREAD

**Issue by valentinaandrade** [rubenarslan/codebook#64]
Hello 
I hope you are very well. I recently notified that the codebook generator is no longer working. The problem indicated according to the application is:

"Error: Package "rio" needed for this function to work. Please install it."

The problem happens either when you are loading data in csv or dta. As a user of the generator, you are unable to install packages.

**Comment by rubenarslan** [comment]
Hi @valentinaandrade, the generator at https://codebook.formr.org seems to working alright. I had a link to a broken generator on ocpu.io in the docs for a while, but removed it a few months ago. Which generator were you using and where did you click the link (so I can correct the link)?

**Comment by valentinaandrade** [comment]
Hi @rubenarslan Thank you very much for the anwser. I use [https://rubenarslan.github.io/codebook/](https://rubenarslan.github.io/codebook/) and [https://rubenarslan.ocpu.io/codebook/www/](https://rubenarslan.ocpu.io/codebook/www/) from the [docs](https://rubenarslan.github.io/codebook/index.html)

Probably this address is an old link (If I am not wrong). 
PS: Thanks for the packages that you have developed. I love formr and codebook.

**Comment by rubenarslan** [comment]
Thanks for pointing me to the link. forgot to fix it there! And great that cb and formr are useful for you!
