### ISSUE TITLE
Missing dependency ('future' package)

### ISSUE THREAD

**Issue by ferreira-santos** [rubenarslan/codebook#65]
First use of the package, installed it and ran the codebook() function (on an SPSS imported dataset) and got the following error:
> Error in loadNamespace(name) : there is no package called ‘future’

Manually installed the package "future" and then the codebook() ran normally.

Noticed in the changelog that there was a recent change in how dependencies are handled, perhaps that is the cause of this issue?

**Comment by LukasWallrich** [comment]
Great package, but this still tripped me up - it might be best if codebooks could be generated without future, but as it stands, this should probably be Depends rather than Suggests?

**Comment by rubenarslan** [comment]
moved future to imports
