### ISSUE TITLE
anoymous multi-line function in "aggregate_and_document_scale" leads to an error

### ISSUE THREAD

**Issue by nsunami** [rubenarslan/codebook#69]
`codebook()` was failing with the `Error: Argument 1 must have names` for `bind_rows()`.
After some investigation, I found that the error is caused by my anonymous function in `aggregate_and_document_scale()`

I got a function like:
```
df$my_scale <- df %>% select(var1:var8) %>%
  aggregate_and_document_scale(fun = function(x){
  rowMeans(x, na.rm = TRUE)
})
```

But, it was producing labels like
```
attr(,"label")
[1] "8 my_scale items aggregated by function(x) {"               
[2] "8 my_scale items aggregated by     rowMeans(x, na.rm = TRUE)"
[3] "8 my_scale items aggregated by }"                           
```

I declared a named function instead, and it worked just fine, like below.

```
rowMeansNarm <- function(x){
  rowMeans(x, na.rm = TRUE)
}
df$my_scale <- df %>% select(var1:var8) %>%
  aggregate_and_document_scale(fun = rowMeansNarm)

```

It seems like each line of the anonymous function is currently treated as separate labels.

**Comment by HeatherUrry** [comment]
Hello Nami and Ruben! 

I'm encountering the same error (`Error: Argument 1 must have names` for `bind_rows()`) but I can't figure out how to solve it. By poking through codebook's R scripts, I see that the metadata.R file calls the `aggregate_and_document_scale()` function. But I can't find metadata.R in the codebook library on my computer to toy around with the code. Wondering if someone can point me in the right direction.

H.

**Comment by nsunami** [comment]
Hi Heather! I'm happy to take a look at your example if you can share it somewhere. My solution was to create another function for the `fun` argument (to remove the argument `na.rm=TRUE`). But I'm not sure if this solution applies to your case. 

 `metadata.R` is available on this repo—[here](https://github.com/rubenarslan/codebook/blob/5f1853684258cb2a5ed4448524535e8b0e9c2175/R/metadata.R#L120) is the part that the `aggregate_and_document_scale` function is being declared.

**Comment by HeatherUrry** [comment]
Thanks, Nami! I realize now that I was fundamentally misunderstanding something. My code never calls `aggregate_and_document_scale()` so that can't be the source of the error for me. :\ 

When I backtrace the error, it appears to be an issue in codebook_table.R. Still sleuthing over here.

**Comment by HeatherUrry** [comment]
Well, I doubt anybody's keeping track but, for the record, I got smart and realized that something I was doing with the data after importing from SPSS but before generating the codebook was introducing the `Error: Argument 1 must have names` message. After deleting extraneous code, the codebook generates without errors. I don't exactly know what I was doing that was problematic but it works now and I'm gonna go with it.

**Comment by rubenarslan** [comment]
Hi @HeatherUrry and @nsunami. I think I know how to fix the first error,
but it'd help me if you can create a small reproducible example of the
second error for me Heather.

**Comment by HeatherUrry** [comment]
Hi @rubenarslan, Thanks for getting back to me about this. I deleted the code that led to the error so I can't easily backtrace which specific code was problematic. Sorry! If I end up tracing it enough to put together a reproducible example, I'll let you know.

H.
